# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\Users\\Rostislav\\Desktop\\Rostislav\\PyCharm_programms\\GameReflection\\Game_Reflection'],
             binaries=[],
             datas=[('DataBases\\Level10_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level11_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level12_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level13_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level14_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level15_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level16_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level17_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level18_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level19_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level1_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level20_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level21_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level22_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level23_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level24_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level25_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level26_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level27_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level28_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level29_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level2_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level30_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level3_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level4_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level5_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level6_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level7_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level8_StartModel.csv', 'DataBases'),
                    ('DataBases\\Level9_StartModel.csv', 'DataBases'),
                    ('Images\\Block.png', 'Images'),
                    ('Images\\Blocks_rules.png', 'Images'),
                    ('Images\\Block_border.png', 'Images'),
                    ('Images\\Border.png', 'Images'),
                    ('Images\\Bricked_block.png', 'Images'),
                    ('Images\\Bricked_block_crushing.png', 'Images'),
                    ('Images\\Cursor.png', 'Images'),
                    ('Images\\Death_block.png', 'Images'),
                    ('Images\\Delete.png', 'Images'),
                    ('Images\\Delete_light.png', 'Images'),
                    ('Images\\Exit.png', 'Images'),
                    ('Images\\Exit_light.png', 'Images'),
                    ('Images\\Exploding_block.png', 'Images'),
                    ('Images\\Exploding_block_crushing_sprites.png', 'Images'),
                    ('Images\\Fone.png', 'Images'),
                    ('Images\\Game_over.png', 'Images'),
                    ('Images\\Health_treasure.png', 'Images'),
                    ('Images\\Info.png', 'Images'),
                    ('Images\\Info_light.png', 'Images'),
                    ('Images\\Long_maker.png', 'Images'),
                    ('Images\\Long_platform.png', 'Images'),
                    ('Images\\Main_rules.png', 'Images'),
                    ('Images\\None.png', 'Images'),
                    ('Images\\Platform.png', 'Images'),
                    ('Images\\Platform_crushing_1.png', 'Images'),
                    ('Images\\Platform_crushing_2.png', 'Images'),
                    ('Images\\Ref_logo.png', 'Images'),
                    ('Images\\Sc_block.png', 'Images'),
                    ('Images\\Settings.png', 'Images'),
                    ('Images\\Settings_light.png', 'Images'),
                    ('Images\\Short_maker.png', 'Images'),
                    ('Images\\Short_platform.png', 'Images'),
                    ('Images\\Treasure.png', 'Images'),
                    ('Images\\Treasures_rules.png', 'Images'),
                    ('Images\\Triplex.png', 'Images'),
                    ('Images\\User_bear.jpg', 'Images'),
                    ('Images\\User_cat.jpg', 'Images'),
                    ('Images\\User_dragon.jpg', 'Images'),
                    ('Images\\User_phoenix.jpg', 'Images'),
                    ('Images\\You_win.png', 'Images'),
                    ('Sounds\\collide.mp3', 'Sounds'),
                    ('Sounds\\crush.mp3', 'Sounds'),
                    ('Sounds\\death_collide.mp3', 'Sounds'),
                    ('Sounds\\game_over.mp3', 'Sounds'),
                    ('Sounds\\life_added.mp3', 'Sounds'),
                    ('Sounds\\main_fone.mp3', 'Sounds'),
                    ('Sounds\\platform_changed.mp3', 'Sounds'),
                    ('Sounds\\platform_crushing.mp3', 'Sounds'),
                    ('Sounds\\play_fone.mp3', 'Sounds'),
                    ('Sounds\\treasure_on_platform.mp3', 'Sounds'),
                    ('Sounds\\win.mp3', 'Sounds')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Reflection',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False, icon='C:\\Users\\Rostislav\\Desktop\\Rostislav\\PyCharm_programms\\GameReflection\\Game_Reflection\\Images\\Ref_logo.ico')
